#############################################################################
# Makefile for building: icp
# Generated by qmake (3.1) (Qt 5.9.4)
# Project:  icp.pro
# Template: app
# Command: /usr/bin/qmake-qt5 -o Makefile icp.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=gnu++14 -Wno-expansion-to-defined -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtXml -isystem /usr/include/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib64/qt5/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake-qt5
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake-qt5 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake-qt5 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = icp1.0.0
DISTDIR = /home/rhulka/programovani/ICP/ICP/.tmp/icp1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lQt5Widgets -lQt5Gui -lQt5Xml -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Block/AbstractBlock.cpp \
		Port/Port.cpp \
		Block/BlocksFactory.cpp \
		Block/FillValuesBlock.cpp \
		Block/Blocks/Aadder1w1a2w1to1w1a2w2a3w3.cpp \
		Block/Blocks/Adder.cpp \
		Block/Blocks/Adder1w1a2w2a3w3to1w1a2w1.cpp \
		Block/Blocks/Adder1w2to1w1.cpp \
		Block/Blocks/Adder1w3to1w1a2w1.cpp \
		Block/Blocks/Divider.cpp \
		Block/Blocks/Multiplier.cpp \
		Block/Blocks/Round.cpp \
		Block/Blocks/Subtractor.cpp \
		Block/Blocks/WaterLaboratory.cpp \
		Type/AbstractType.cpp \
		Type/RegisterTypes.cpp \
		Type/Types/CarbonDioxide.cpp \
		Type/Types/Hydrogenium.cpp \
		Type/Types/Methan.cpp \
		Type/Types/OneDecimalNumber.cpp \
		Type/Types/Oxid.cpp \
		Type/Types/ThreeDecimalNumbers.cpp \
		Type/Types/TwoDecimalNumbers.cpp \
		Type/Types/Water.cpp \
		Port/FillValuesPort.cpp \
		Wire/Wire.cpp \
		Main.cpp \
		MainWindow.cpp qrc_Resources.cpp \
		moc_FillValuesBlock.cpp \
		moc_FillValuesPort.cpp \
		moc_MainWindow.cpp
OBJECTS       = AbstractBlock.o \
		Port.o \
		BlocksFactory.o \
		FillValuesBlock.o \
		Aadder1w1a2w1to1w1a2w2a3w3.o \
		Adder.o \
		Adder1w1a2w2a3w3to1w1a2w1.o \
		Adder1w2to1w1.o \
		Adder1w3to1w1a2w1.o \
		Divider.o \
		Multiplier.o \
		Round.o \
		Subtractor.o \
		WaterLaboratory.o \
		AbstractType.o \
		RegisterTypes.o \
		CarbonDioxide.o \
		Hydrogenium.o \
		Methan.o \
		OneDecimalNumber.o \
		Oxid.o \
		ThreeDecimalNumbers.o \
		TwoDecimalNumbers.o \
		Water.o \
		FillValuesPort.o \
		Wire.o \
		Main.o \
		MainWindow.o \
		qrc_Resources.o \
		moc_FillValuesBlock.o \
		moc_FillValuesPort.o \
		moc_MainWindow.o
DIST          = /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/toolchain.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		icp.pro Block/AbstractBlock.h \
		Port/Port.h \
		Block/BlocksFactory.h \
		Block/FillValuesBlock.h \
		Block/Blocks/Adder.h \
		Block/Blocks/Adder1w1a2w1to1w1a2w2a3w3.h \
		Block/Blocks/Adder1w1a2w2a3w3to1w1a2w1.h \
		Block/Blocks/Adder1w2to1w1.h \
		Block/Blocks/Adder1w3to1w1a2w1.h \
		Block/Blocks/Divider.h \
		Block/Blocks/Multiplier.h \
		Block/Blocks/Round.h \
		Block/Blocks/Subtractor.h \
		Block/Blocks/WaterLaboratory.h \
		Type/AbstractType.h \
		Type/RegisterTypes.h \
		Type/Types/CarbonDioxide.h \
		Type/Types/Hydrogenium.h \
		Type/Types/Methan.h \
		Type/Types/OneDecimalNumber.h \
		Type/Types/Oxid.h \
		Type/Types/ThreeDecimalNumbers.h \
		Type/Types/TwoDecimalNumbers.h \
		Type/Types/Water.h \
		Port/FillValuesPort.h \
		Wire/Wire.h \
		MainWindow.h Block/AbstractBlock.cpp \
		Port/Port.cpp \
		Block/BlocksFactory.cpp \
		Block/FillValuesBlock.cpp \
		Block/Blocks/Aadder1w1a2w1to1w1a2w2a3w3.cpp \
		Block/Blocks/Adder.cpp \
		Block/Blocks/Adder1w1a2w2a3w3to1w1a2w1.cpp \
		Block/Blocks/Adder1w2to1w1.cpp \
		Block/Blocks/Adder1w3to1w1a2w1.cpp \
		Block/Blocks/Divider.cpp \
		Block/Blocks/Multiplier.cpp \
		Block/Blocks/Round.cpp \
		Block/Blocks/Subtractor.cpp \
		Block/Blocks/WaterLaboratory.cpp \
		Type/AbstractType.cpp \
		Type/RegisterTypes.cpp \
		Type/Types/CarbonDioxide.cpp \
		Type/Types/Hydrogenium.cpp \
		Type/Types/Methan.cpp \
		Type/Types/OneDecimalNumber.cpp \
		Type/Types/Oxid.cpp \
		Type/Types/ThreeDecimalNumbers.cpp \
		Type/Types/TwoDecimalNumbers.cpp \
		Type/Types/Water.cpp \
		Port/FillValuesPort.cpp \
		Wire/Wire.cpp \
		Main.cpp \
		MainWindow.cpp
QMAKE_TARGET  = icp
DESTDIR       = 
TARGET        = icp


first: all
####### Build rules

$(TARGET): ui_MainWindow.h ui_FillValues.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: icp.pro /usr/lib64/qt5/mkspecs/linux-g++/qmake.conf /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/toolchain.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		icp.pro \
		Resources.qrc \
		/usr/lib64/libQt5Widgets.prl \
		/usr/lib64/libQt5Gui.prl \
		/usr/lib64/libQt5Xml.prl \
		/usr/lib64/libQt5Core.prl
	$(QMAKE) -o Makefile icp.pro
/usr/lib64/qt5/mkspecs/features/spec_pre.prf:
/usr/lib64/qt5/mkspecs/common/unix.conf:
/usr/lib64/qt5/mkspecs/common/linux.conf:
/usr/lib64/qt5/mkspecs/common/sanitize.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt5/mkspecs/common/g++-base.conf:
/usr/lib64/qt5/mkspecs/common/g++-unix.conf:
/usr/lib64/qt5/mkspecs/qconfig.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib64/qt5/mkspecs/features/qt_functions.prf:
/usr/lib64/qt5/mkspecs/features/qt_config.prf:
/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib64/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt5/mkspecs/features/toolchain.prf:
/usr/lib64/qt5/mkspecs/features/default_pre.prf:
/usr/lib64/qt5/mkspecs/features/resolve_config.prf:
/usr/lib64/qt5/mkspecs/features/default_post.prf:
/usr/lib64/qt5/mkspecs/features/warn_on.prf:
/usr/lib64/qt5/mkspecs/features/qt.prf:
/usr/lib64/qt5/mkspecs/features/resources.prf:
/usr/lib64/qt5/mkspecs/features/moc.prf:
/usr/lib64/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib64/qt5/mkspecs/features/uic.prf:
/usr/lib64/qt5/mkspecs/features/unix/thread.prf:
/usr/lib64/qt5/mkspecs/features/qmake_use.prf:
/usr/lib64/qt5/mkspecs/features/file_copies.prf:
/usr/lib64/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib64/qt5/mkspecs/features/exceptions.prf:
/usr/lib64/qt5/mkspecs/features/yacc.prf:
/usr/lib64/qt5/mkspecs/features/lex.prf:
icp.pro:
Resources.qrc:
/usr/lib64/libQt5Widgets.prl:
/usr/lib64/libQt5Gui.prl:
/usr/lib64/libQt5Xml.prl:
/usr/lib64/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile icp.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents Resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib64/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents Block/AbstractBlock.h Port/Port.h Block/BlocksFactory.h Block/FillValuesBlock.h Block/Blocks/Adder.h Block/Blocks/Adder1w1a2w1to1w1a2w2a3w3.h Block/Blocks/Adder1w1a2w2a3w3to1w1a2w1.h Block/Blocks/Adder1w2to1w1.h Block/Blocks/Adder1w3to1w1a2w1.h Block/Blocks/Divider.h Block/Blocks/Multiplier.h Block/Blocks/Round.h Block/Blocks/Subtractor.h Block/Blocks/WaterLaboratory.h Type/AbstractType.h Type/RegisterTypes.h Type/Types/CarbonDioxide.h Type/Types/Hydrogenium.h Type/Types/Methan.h Type/Types/OneDecimalNumber.h Type/Types/Oxid.h Type/Types/ThreeDecimalNumbers.h Type/Types/TwoDecimalNumbers.h Type/Types/Water.h Port/FillValuesPort.h Wire/Wire.h MainWindow.h $(DISTDIR)/
	$(COPY_FILE) --parents Block/AbstractBlock.cpp Port/Port.cpp Block/BlocksFactory.cpp Block/FillValuesBlock.cpp Block/Blocks/Aadder1w1a2w1to1w1a2w2a3w3.cpp Block/Blocks/Adder.cpp Block/Blocks/Adder1w1a2w2a3w3to1w1a2w1.cpp Block/Blocks/Adder1w2to1w1.cpp Block/Blocks/Adder1w3to1w1a2w1.cpp Block/Blocks/Divider.cpp Block/Blocks/Multiplier.cpp Block/Blocks/Round.cpp Block/Blocks/Subtractor.cpp Block/Blocks/WaterLaboratory.cpp Type/AbstractType.cpp Type/RegisterTypes.cpp Type/Types/CarbonDioxide.cpp Type/Types/Hydrogenium.cpp Type/Types/Methan.cpp Type/Types/OneDecimalNumber.cpp Type/Types/Oxid.cpp Type/Types/ThreeDecimalNumbers.cpp Type/Types/TwoDecimalNumbers.cpp Type/Types/Water.cpp Port/FillValuesPort.cpp Wire/Wire.cpp Main.cpp MainWindow.cpp $(DISTDIR)/
	$(COPY_FILE) --parents MainWindow.ui FillValues.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_Resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_Resources.cpp
qrc_Resources.cpp: Resources.qrc \
		/usr/lib64/qt5/bin/rcc \
		Resources/stop.png \
		Resources/Adder1w1a2w1to1w1a2w2a3w3.png \
		Resources/Adder1w2to1w1.png \
		Resources/Adder1w1a2w2a3w3to1w1a2w1.png \
		Resources/Multiplier.png \
		Resources/Round.png \
		Resources/next.png \
		Resources/Adder1w3to1w1a2w1.png \
		Resources/Divider.png \
		Resources/WaterLaboratory.png \
		Resources/finish.png \
		Resources/Adder.png \
		Resources/Subtractor.png
	/usr/lib64/qt5/bin/rcc -name Resources Resources.qrc -o qrc_Resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib64/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -std=gnu++14 -Wno-expansion-to-defined -O2 -Wall -W -dM -E -o moc_predefs.h /usr/lib64/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_FillValuesBlock.cpp moc_FillValuesPort.cpp moc_MainWindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_FillValuesBlock.cpp moc_FillValuesPort.cpp moc_MainWindow.cpp
moc_FillValuesBlock.cpp: ui_FillValues.h \
		Block/AbstractBlock.h \
		Port/Port.h \
		Port/FillValuesPort.h \
		Wire/Wire.h \
		MainWindow.h \
		ui_MainWindow.h \
		Type/RegisterTypes.h \
		Type/Types/OneDecimalNumber.h \
		Type/AbstractType.h \
		Type/Types/TwoDecimalNumbers.h \
		Type/Types/ThreeDecimalNumbers.h \
		Type/Types/Hydrogenium.h \
		Type/Types/Oxid.h \
		Type/Types/Methan.h \
		Type/Types/CarbonDioxide.h \
		Type/Types/Water.h \
		Block/FillValuesBlock.h \
		Block/FillValuesBlock.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/rhulka/programovani/ICP/ICP -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-redhat-linux -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-redhat-linux/7/include -I/usr/local/include -I/usr/include Block/FillValuesBlock.h -o moc_FillValuesBlock.cpp

moc_FillValuesPort.cpp: ui_FillValues.h \
		Port/Port.h \
		Port/FillValuesPort.h \
		Wire/Wire.h \
		MainWindow.h \
		ui_MainWindow.h \
		Block/AbstractBlock.h \
		Block/FillValuesBlock.h \
		Type/RegisterTypes.h \
		Type/Types/OneDecimalNumber.h \
		Type/AbstractType.h \
		Type/Types/TwoDecimalNumbers.h \
		Type/Types/ThreeDecimalNumbers.h \
		Type/Types/Hydrogenium.h \
		Type/Types/Oxid.h \
		Type/Types/Methan.h \
		Type/Types/CarbonDioxide.h \
		Type/Types/Water.h \
		Port/FillValuesPort.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/rhulka/programovani/ICP/ICP -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-redhat-linux -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-redhat-linux/7/include -I/usr/local/include -I/usr/include Port/FillValuesPort.h -o moc_FillValuesPort.cpp

moc_MainWindow.cpp: ui_MainWindow.h \
		Block/AbstractBlock.h \
		Port/Port.h \
		Port/FillValuesPort.h \
		ui_FillValues.h \
		Wire/Wire.h \
		MainWindow.h \
		Type/RegisterTypes.h \
		Type/Types/OneDecimalNumber.h \
		Type/AbstractType.h \
		Type/Types/TwoDecimalNumbers.h \
		Type/Types/ThreeDecimalNumbers.h \
		Type/Types/Hydrogenium.h \
		Type/Types/Oxid.h \
		Type/Types/Methan.h \
		Type/Types/CarbonDioxide.h \
		Type/Types/Water.h \
		Block/FillValuesBlock.h \
		MainWindow.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/rhulka/programovani/ICP/ICP -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-redhat-linux -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-redhat-linux/7/include -I/usr/local/include -I/usr/include MainWindow.h -o moc_MainWindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_MainWindow.h ui_FillValues.h
compiler_uic_clean:
	-$(DEL_FILE) ui_MainWindow.h ui_FillValues.h
ui_MainWindow.h: MainWindow.ui \
		/usr/lib64/qt5/bin/uic
	/usr/lib64/qt5/bin/uic MainWindow.ui -o ui_MainWindow.h

ui_FillValues.h: FillValues.ui \
		/usr/lib64/qt5/bin/uic
	/usr/lib64/qt5/bin/uic FillValues.ui -o ui_FillValues.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

AbstractBlock.o: Block/AbstractBlock.cpp Block/AbstractBlock.h \
		Port/Port.h \
		Port/FillValuesPort.h \
		ui_FillValues.h \
		Wire/Wire.h \
		MainWindow.h \
		ui_MainWindow.h \
		Type/RegisterTypes.h \
		Type/Types/OneDecimalNumber.h \
		Type/AbstractType.h \
		Type/Types/TwoDecimalNumbers.h \
		Type/Types/ThreeDecimalNumbers.h \
		Type/Types/Hydrogenium.h \
		Type/Types/Oxid.h \
		Type/Types/Methan.h \
		Type/Types/CarbonDioxide.h \
		Type/Types/Water.h \
		Block/FillValuesBlock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AbstractBlock.o Block/AbstractBlock.cpp

Port.o: Port/Port.cpp Port/Port.h \
		Port/FillValuesPort.h \
		ui_FillValues.h \
		Wire/Wire.h \
		MainWindow.h \
		ui_MainWindow.h \
		Block/AbstractBlock.h \
		Block/FillValuesBlock.h \
		Type/RegisterTypes.h \
		Type/Types/OneDecimalNumber.h \
		Type/AbstractType.h \
		Type/Types/TwoDecimalNumbers.h \
		Type/Types/ThreeDecimalNumbers.h \
		Type/Types/Hydrogenium.h \
		Type/Types/Oxid.h \
		Type/Types/Methan.h \
		Type/Types/CarbonDioxide.h \
		Type/Types/Water.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Port.o Port/Port.cpp

BlocksFactory.o: Block/BlocksFactory.cpp Block/BlocksFactory.h \
		Block/Blocks/Adder.h \
		Block/AbstractBlock.h \
		Port/Port.h \
		Port/FillValuesPort.h \
		ui_FillValues.h \
		Wire/Wire.h \
		MainWindow.h \
		ui_MainWindow.h \
		Type/RegisterTypes.h \
		Type/Types/OneDecimalNumber.h \
		Type/AbstractType.h \
		Type/Types/TwoDecimalNumbers.h \
		Type/Types/ThreeDecimalNumbers.h \
		Type/Types/Hydrogenium.h \
		Type/Types/Oxid.h \
		Type/Types/Methan.h \
		Type/Types/CarbonDioxide.h \
		Type/Types/Water.h \
		Block/FillValuesBlock.h \
		Block/Blocks/Subtractor.h \
		Block/Blocks/Multiplier.h \
		Block/Blocks/Divider.h \
		Block/Blocks/Adder1w1a2w1to1w1a2w2a3w3.h \
		Block/Blocks/Adder1w1a2w2a3w3to1w1a2w1.h \
		Block/Blocks/Adder1w2to1w1.h \
		Block/Blocks/Adder1w3to1w1a2w1.h \
		Block/Blocks/Round.h \
		Block/Blocks/WaterLaboratory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o BlocksFactory.o Block/BlocksFactory.cpp

FillValuesBlock.o: Block/FillValuesBlock.cpp Block/FillValuesBlock.h \
		ui_FillValues.h \
		Block/AbstractBlock.h \
		Port/Port.h \
		Port/FillValuesPort.h \
		Wire/Wire.h \
		MainWindow.h \
		ui_MainWindow.h \
		Type/RegisterTypes.h \
		Type/Types/OneDecimalNumber.h \
		Type/AbstractType.h \
		Type/Types/TwoDecimalNumbers.h \
		Type/Types/ThreeDecimalNumbers.h \
		Type/Types/Hydrogenium.h \
		Type/Types/Oxid.h \
		Type/Types/Methan.h \
		Type/Types/CarbonDioxide.h \
		Type/Types/Water.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FillValuesBlock.o Block/FillValuesBlock.cpp

Aadder1w1a2w1to1w1a2w2a3w3.o: Block/Blocks/Aadder1w1a2w1to1w1a2w2a3w3.cpp Block/Blocks/Adder1w1a2w1to1w1a2w2a3w3.h \
		Block/AbstractBlock.h \
		Port/Port.h \
		Port/FillValuesPort.h \
		ui_FillValues.h \
		Wire/Wire.h \
		MainWindow.h \
		ui_MainWindow.h \
		Type/RegisterTypes.h \
		Type/Types/OneDecimalNumber.h \
		Type/AbstractType.h \
		Type/Types/TwoDecimalNumbers.h \
		Type/Types/ThreeDecimalNumbers.h \
		Type/Types/Hydrogenium.h \
		Type/Types/Oxid.h \
		Type/Types/Methan.h \
		Type/Types/CarbonDioxide.h \
		Type/Types/Water.h \
		Block/FillValuesBlock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Aadder1w1a2w1to1w1a2w2a3w3.o Block/Blocks/Aadder1w1a2w1to1w1a2w2a3w3.cpp

Adder.o: Block/Blocks/Adder.cpp Block/Blocks/Adder.h \
		Block/AbstractBlock.h \
		Port/Port.h \
		Port/FillValuesPort.h \
		ui_FillValues.h \
		Wire/Wire.h \
		MainWindow.h \
		ui_MainWindow.h \
		Type/RegisterTypes.h \
		Type/Types/OneDecimalNumber.h \
		Type/AbstractType.h \
		Type/Types/TwoDecimalNumbers.h \
		Type/Types/ThreeDecimalNumbers.h \
		Type/Types/Hydrogenium.h \
		Type/Types/Oxid.h \
		Type/Types/Methan.h \
		Type/Types/CarbonDioxide.h \
		Type/Types/Water.h \
		Block/FillValuesBlock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Adder.o Block/Blocks/Adder.cpp

Adder1w1a2w2a3w3to1w1a2w1.o: Block/Blocks/Adder1w1a2w2a3w3to1w1a2w1.cpp Block/Blocks/Adder1w1a2w2a3w3to1w1a2w1.h \
		Block/AbstractBlock.h \
		Port/Port.h \
		Port/FillValuesPort.h \
		ui_FillValues.h \
		Wire/Wire.h \
		MainWindow.h \
		ui_MainWindow.h \
		Type/RegisterTypes.h \
		Type/Types/OneDecimalNumber.h \
		Type/AbstractType.h \
		Type/Types/TwoDecimalNumbers.h \
		Type/Types/ThreeDecimalNumbers.h \
		Type/Types/Hydrogenium.h \
		Type/Types/Oxid.h \
		Type/Types/Methan.h \
		Type/Types/CarbonDioxide.h \
		Type/Types/Water.h \
		Block/FillValuesBlock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Adder1w1a2w2a3w3to1w1a2w1.o Block/Blocks/Adder1w1a2w2a3w3to1w1a2w1.cpp

Adder1w2to1w1.o: Block/Blocks/Adder1w2to1w1.cpp Block/Blocks/Adder1w2to1w1.h \
		Block/AbstractBlock.h \
		Port/Port.h \
		Port/FillValuesPort.h \
		ui_FillValues.h \
		Wire/Wire.h \
		MainWindow.h \
		ui_MainWindow.h \
		Type/RegisterTypes.h \
		Type/Types/OneDecimalNumber.h \
		Type/AbstractType.h \
		Type/Types/TwoDecimalNumbers.h \
		Type/Types/ThreeDecimalNumbers.h \
		Type/Types/Hydrogenium.h \
		Type/Types/Oxid.h \
		Type/Types/Methan.h \
		Type/Types/CarbonDioxide.h \
		Type/Types/Water.h \
		Block/FillValuesBlock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Adder1w2to1w1.o Block/Blocks/Adder1w2to1w1.cpp

Adder1w3to1w1a2w1.o: Block/Blocks/Adder1w3to1w1a2w1.cpp Block/Blocks/Adder1w3to1w1a2w1.h \
		Block/AbstractBlock.h \
		Port/Port.h \
		Port/FillValuesPort.h \
		ui_FillValues.h \
		Wire/Wire.h \
		MainWindow.h \
		ui_MainWindow.h \
		Type/RegisterTypes.h \
		Type/Types/OneDecimalNumber.h \
		Type/AbstractType.h \
		Type/Types/TwoDecimalNumbers.h \
		Type/Types/ThreeDecimalNumbers.h \
		Type/Types/Hydrogenium.h \
		Type/Types/Oxid.h \
		Type/Types/Methan.h \
		Type/Types/CarbonDioxide.h \
		Type/Types/Water.h \
		Block/FillValuesBlock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Adder1w3to1w1a2w1.o Block/Blocks/Adder1w3to1w1a2w1.cpp

Divider.o: Block/Blocks/Divider.cpp Block/Blocks/Divider.h \
		Block/AbstractBlock.h \
		Port/Port.h \
		Port/FillValuesPort.h \
		ui_FillValues.h \
		Wire/Wire.h \
		MainWindow.h \
		ui_MainWindow.h \
		Type/RegisterTypes.h \
		Type/Types/OneDecimalNumber.h \
		Type/AbstractType.h \
		Type/Types/TwoDecimalNumbers.h \
		Type/Types/ThreeDecimalNumbers.h \
		Type/Types/Hydrogenium.h \
		Type/Types/Oxid.h \
		Type/Types/Methan.h \
		Type/Types/CarbonDioxide.h \
		Type/Types/Water.h \
		Block/FillValuesBlock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Divider.o Block/Blocks/Divider.cpp

Multiplier.o: Block/Blocks/Multiplier.cpp Block/Blocks/Multiplier.h \
		Block/AbstractBlock.h \
		Port/Port.h \
		Port/FillValuesPort.h \
		ui_FillValues.h \
		Wire/Wire.h \
		MainWindow.h \
		ui_MainWindow.h \
		Type/RegisterTypes.h \
		Type/Types/OneDecimalNumber.h \
		Type/AbstractType.h \
		Type/Types/TwoDecimalNumbers.h \
		Type/Types/ThreeDecimalNumbers.h \
		Type/Types/Hydrogenium.h \
		Type/Types/Oxid.h \
		Type/Types/Methan.h \
		Type/Types/CarbonDioxide.h \
		Type/Types/Water.h \
		Block/FillValuesBlock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Multiplier.o Block/Blocks/Multiplier.cpp

Round.o: Block/Blocks/Round.cpp Block/Blocks/Round.h \
		Block/AbstractBlock.h \
		Port/Port.h \
		Port/FillValuesPort.h \
		ui_FillValues.h \
		Wire/Wire.h \
		MainWindow.h \
		ui_MainWindow.h \
		Type/RegisterTypes.h \
		Type/Types/OneDecimalNumber.h \
		Type/AbstractType.h \
		Type/Types/TwoDecimalNumbers.h \
		Type/Types/ThreeDecimalNumbers.h \
		Type/Types/Hydrogenium.h \
		Type/Types/Oxid.h \
		Type/Types/Methan.h \
		Type/Types/CarbonDioxide.h \
		Type/Types/Water.h \
		Block/FillValuesBlock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Round.o Block/Blocks/Round.cpp

Subtractor.o: Block/Blocks/Subtractor.cpp Block/Blocks/Subtractor.h \
		Block/AbstractBlock.h \
		Port/Port.h \
		Port/FillValuesPort.h \
		ui_FillValues.h \
		Wire/Wire.h \
		MainWindow.h \
		ui_MainWindow.h \
		Type/RegisterTypes.h \
		Type/Types/OneDecimalNumber.h \
		Type/AbstractType.h \
		Type/Types/TwoDecimalNumbers.h \
		Type/Types/ThreeDecimalNumbers.h \
		Type/Types/Hydrogenium.h \
		Type/Types/Oxid.h \
		Type/Types/Methan.h \
		Type/Types/CarbonDioxide.h \
		Type/Types/Water.h \
		Block/FillValuesBlock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Subtractor.o Block/Blocks/Subtractor.cpp

WaterLaboratory.o: Block/Blocks/WaterLaboratory.cpp Block/Blocks/WaterLaboratory.h \
		Block/AbstractBlock.h \
		Port/Port.h \
		Port/FillValuesPort.h \
		ui_FillValues.h \
		Wire/Wire.h \
		MainWindow.h \
		ui_MainWindow.h \
		Type/RegisterTypes.h \
		Type/Types/OneDecimalNumber.h \
		Type/AbstractType.h \
		Type/Types/TwoDecimalNumbers.h \
		Type/Types/ThreeDecimalNumbers.h \
		Type/Types/Hydrogenium.h \
		Type/Types/Oxid.h \
		Type/Types/Methan.h \
		Type/Types/CarbonDioxide.h \
		Type/Types/Water.h \
		Block/FillValuesBlock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WaterLaboratory.o Block/Blocks/WaterLaboratory.cpp

AbstractType.o: Type/AbstractType.cpp Type/AbstractType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AbstractType.o Type/AbstractType.cpp

RegisterTypes.o: Type/RegisterTypes.cpp Type/RegisterTypes.h \
		Type/Types/OneDecimalNumber.h \
		Type/AbstractType.h \
		Type/Types/TwoDecimalNumbers.h \
		Type/Types/ThreeDecimalNumbers.h \
		Type/Types/Hydrogenium.h \
		Type/Types/Oxid.h \
		Type/Types/Methan.h \
		Type/Types/CarbonDioxide.h \
		Type/Types/Water.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RegisterTypes.o Type/RegisterTypes.cpp

CarbonDioxide.o: Type/Types/CarbonDioxide.cpp Type/Types/CarbonDioxide.h \
		Type/AbstractType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CarbonDioxide.o Type/Types/CarbonDioxide.cpp

Hydrogenium.o: Type/Types/Hydrogenium.cpp Type/Types/Hydrogenium.h \
		Type/AbstractType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Hydrogenium.o Type/Types/Hydrogenium.cpp

Methan.o: Type/Types/Methan.cpp Type/Types/Methan.h \
		Type/AbstractType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Methan.o Type/Types/Methan.cpp

OneDecimalNumber.o: Type/Types/OneDecimalNumber.cpp Type/Types/OneDecimalNumber.h \
		Type/AbstractType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o OneDecimalNumber.o Type/Types/OneDecimalNumber.cpp

Oxid.o: Type/Types/Oxid.cpp Type/Types/Oxid.h \
		Type/AbstractType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Oxid.o Type/Types/Oxid.cpp

ThreeDecimalNumbers.o: Type/Types/ThreeDecimalNumbers.cpp Type/Types/ThreeDecimalNumbers.h \
		Type/AbstractType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ThreeDecimalNumbers.o Type/Types/ThreeDecimalNumbers.cpp

TwoDecimalNumbers.o: Type/Types/TwoDecimalNumbers.cpp Type/Types/TwoDecimalNumbers.h \
		Type/AbstractType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TwoDecimalNumbers.o Type/Types/TwoDecimalNumbers.cpp

Water.o: Type/Types/Water.cpp Type/Types/Water.h \
		Type/AbstractType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Water.o Type/Types/Water.cpp

FillValuesPort.o: Port/FillValuesPort.cpp Port/FillValuesPort.h \
		ui_FillValues.h \
		Port/Port.h \
		Wire/Wire.h \
		MainWindow.h \
		ui_MainWindow.h \
		Block/AbstractBlock.h \
		Block/FillValuesBlock.h \
		Type/RegisterTypes.h \
		Type/Types/OneDecimalNumber.h \
		Type/AbstractType.h \
		Type/Types/TwoDecimalNumbers.h \
		Type/Types/ThreeDecimalNumbers.h \
		Type/Types/Hydrogenium.h \
		Type/Types/Oxid.h \
		Type/Types/Methan.h \
		Type/Types/CarbonDioxide.h \
		Type/Types/Water.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o FillValuesPort.o Port/FillValuesPort.cpp

Wire.o: Wire/Wire.cpp Wire/Wire.h \
		MainWindow.h \
		ui_MainWindow.h \
		Block/AbstractBlock.h \
		Port/Port.h \
		Port/FillValuesPort.h \
		ui_FillValues.h \
		Block/FillValuesBlock.h \
		Type/RegisterTypes.h \
		Type/Types/OneDecimalNumber.h \
		Type/AbstractType.h \
		Type/Types/TwoDecimalNumbers.h \
		Type/Types/ThreeDecimalNumbers.h \
		Type/Types/Hydrogenium.h \
		Type/Types/Oxid.h \
		Type/Types/Methan.h \
		Type/Types/CarbonDioxide.h \
		Type/Types/Water.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Wire.o Wire/Wire.cpp

Main.o: Main.cpp MainWindow.h \
		ui_MainWindow.h \
		Block/AbstractBlock.h \
		Port/Port.h \
		Port/FillValuesPort.h \
		ui_FillValues.h \
		Wire/Wire.h \
		Block/FillValuesBlock.h \
		Type/RegisterTypes.h \
		Type/Types/OneDecimalNumber.h \
		Type/AbstractType.h \
		Type/Types/TwoDecimalNumbers.h \
		Type/Types/ThreeDecimalNumbers.h \
		Type/Types/Hydrogenium.h \
		Type/Types/Oxid.h \
		Type/Types/Methan.h \
		Type/Types/CarbonDioxide.h \
		Type/Types/Water.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Main.o Main.cpp

MainWindow.o: MainWindow.cpp MainWindow.h \
		ui_MainWindow.h \
		Block/AbstractBlock.h \
		Port/Port.h \
		Port/FillValuesPort.h \
		ui_FillValues.h \
		Wire/Wire.h \
		Block/FillValuesBlock.h \
		Type/RegisterTypes.h \
		Type/Types/OneDecimalNumber.h \
		Type/AbstractType.h \
		Type/Types/TwoDecimalNumbers.h \
		Type/Types/ThreeDecimalNumbers.h \
		Type/Types/Hydrogenium.h \
		Type/Types/Oxid.h \
		Type/Types/Methan.h \
		Type/Types/CarbonDioxide.h \
		Type/Types/Water.h \
		Block/BlocksFactory.h \
		Block/Blocks/Adder.h \
		Block/Blocks/Subtractor.h \
		Block/Blocks/Multiplier.h \
		Block/Blocks/Divider.h \
		Block/Blocks/Adder1w1a2w1to1w1a2w2a3w3.h \
		Block/Blocks/Adder1w1a2w2a3w3to1w1a2w1.h \
		Block/Blocks/Adder1w2to1w1.h \
		Block/Blocks/Adder1w3to1w1a2w1.h \
		Block/Blocks/Round.h \
		Block/Blocks/WaterLaboratory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o MainWindow.cpp

qrc_Resources.o: qrc_Resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_Resources.o qrc_Resources.cpp

moc_FillValuesBlock.o: moc_FillValuesBlock.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FillValuesBlock.o moc_FillValuesBlock.cpp

moc_FillValuesPort.o: moc_FillValuesPort.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_FillValuesPort.o moc_FillValuesPort.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

