#############################################################################
# Makefile for building: icp
# Generated by qmake (3.1) (Qt 5.9.4)
# Project:  icp.pro
# Template: app
# Command: /usr/bin/qmake-qt5 -o Makefile icp.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=gnu++14 -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib64/qt5/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake-qt5
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake-qt5 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake-qt5 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = icp1.0.0
DISTDIR = /home/rhulka/programovani/ICP/ICP/.tmp/icp1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		Block/abstractBlock.cpp \
		Block/adder.cpp \
		Block/subtractor.cpp \
		Block/multiplier.cpp \
		Block/divider.cpp \
		Block/adder1w1a2w2a3w3to1w1a2w1.cpp \
		Block/adder1w1a2w1to1w1a2w2a3w3.cpp \
		Type/abstractType.cpp \
		Type/onedecimalnumber.cpp \
		Type/twodecimalnumbers.cpp \
		Type/threedecimalnumbers.cpp \
		Port/port.cpp \
		Wire/wire.cpp \
		values.cpp \
		Type/registrtypes.cpp \
		Block/blocksfactory.cpp \
		Block/fillvaluesblock.cpp qrc_resources.cpp \
		moc_mainwindow.cpp \
		moc_port.cpp \
		moc_fillvaluesblock.cpp
OBJECTS       = main.o \
		mainwindow.o \
		abstractBlock.o \
		adder.o \
		subtractor.o \
		multiplier.o \
		divider.o \
		adder1w1a2w2a3w3to1w1a2w1.o \
		adder1w1a2w1to1w1a2w2a3w3.o \
		abstractType.o \
		onedecimalnumber.o \
		twodecimalnumbers.o \
		threedecimalnumbers.o \
		port.o \
		wire.o \
		values.o \
		registrtypes.o \
		blocksfactory.o \
		fillvaluesblock.o \
		qrc_resources.o \
		moc_mainwindow.o \
		moc_port.o \
		moc_fillvaluesblock.o
DIST          = /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/toolchain.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		icp.pro mainwindow.h \
		Port/port.h \
		Block/abstractBlock.h \
		Block/adder.h \
		Block/subtractor.h \
		Block/multiplier.h \
		Block/divider.h \
		Block/adder1w1a2w2a3w3to1w1a2w1.h \
		Block/adder1w1a2w1to1w1a2w2a3w3.h \
		Type/abstractType.h \
		Type/onedecimalnumber.h \
		Type/twodecimalnumbers.h \
		Type/threedecimalnumbers.h \
		Wire/wire.h \
		Type/registrtypes.h \
		Block/blocksfactory.h \
		Block/fillvaluesblock.h main.cpp \
		mainwindow.cpp \
		Block/abstractBlock.cpp \
		Block/adder.cpp \
		Block/subtractor.cpp \
		Block/multiplier.cpp \
		Block/divider.cpp \
		Block/adder1w1a2w2a3w3to1w1a2w1.cpp \
		Block/adder1w1a2w1to1w1a2w2a3w3.cpp \
		Type/abstractType.cpp \
		Type/onedecimalnumber.cpp \
		Type/twodecimalnumbers.cpp \
		Type/threedecimalnumbers.cpp \
		Port/port.cpp \
		Wire/wire.cpp \
		values.cpp \
		Type/registrtypes.cpp \
		Block/blocksfactory.cpp \
		Block/fillvaluesblock.cpp
QMAKE_TARGET  = icp
DESTDIR       = 
TARGET        = icp


first: all
####### Build rules

$(TARGET): ui_mainwindow.h ui_values.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: icp.pro /usr/lib64/qt5/mkspecs/linux-g++/qmake.conf /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/toolchain.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		icp.pro \
		resources.qrc \
		/usr/lib64/libQt5Widgets.prl \
		/usr/lib64/libQt5Gui.prl \
		/usr/lib64/libQt5Core.prl
	$(QMAKE) -o Makefile icp.pro
/usr/lib64/qt5/mkspecs/features/spec_pre.prf:
/usr/lib64/qt5/mkspecs/common/unix.conf:
/usr/lib64/qt5/mkspecs/common/linux.conf:
/usr/lib64/qt5/mkspecs/common/sanitize.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt5/mkspecs/common/g++-base.conf:
/usr/lib64/qt5/mkspecs/common/g++-unix.conf:
/usr/lib64/qt5/mkspecs/qconfig.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib64/qt5/mkspecs/features/qt_functions.prf:
/usr/lib64/qt5/mkspecs/features/qt_config.prf:
/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib64/qt5/mkspecs/features/spec_post.prf:
/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt5/mkspecs/features/toolchain.prf:
/usr/lib64/qt5/mkspecs/features/default_pre.prf:
/usr/lib64/qt5/mkspecs/features/resolve_config.prf:
/usr/lib64/qt5/mkspecs/features/default_post.prf:
/usr/lib64/qt5/mkspecs/features/warn_on.prf:
/usr/lib64/qt5/mkspecs/features/qt.prf:
/usr/lib64/qt5/mkspecs/features/resources.prf:
/usr/lib64/qt5/mkspecs/features/moc.prf:
/usr/lib64/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib64/qt5/mkspecs/features/uic.prf:
/usr/lib64/qt5/mkspecs/features/unix/thread.prf:
/usr/lib64/qt5/mkspecs/features/qmake_use.prf:
/usr/lib64/qt5/mkspecs/features/file_copies.prf:
/usr/lib64/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib64/qt5/mkspecs/features/exceptions.prf:
/usr/lib64/qt5/mkspecs/features/yacc.prf:
/usr/lib64/qt5/mkspecs/features/lex.prf:
icp.pro:
resources.qrc:
/usr/lib64/libQt5Widgets.prl:
/usr/lib64/libQt5Gui.prl:
/usr/lib64/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile icp.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib64/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h Port/port.h Block/abstractBlock.h Block/adder.h Block/subtractor.h Block/multiplier.h Block/divider.h Block/adder1w1a2w2a3w3to1w1a2w1.h Block/adder1w1a2w1to1w1a2w2a3w3.h Type/abstractType.h Type/onedecimalnumber.h Type/twodecimalnumbers.h Type/threedecimalnumbers.h Wire/wire.h Type/registrtypes.h Block/blocksfactory.h Block/fillvaluesblock.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp Block/abstractBlock.cpp Block/adder.cpp Block/subtractor.cpp Block/multiplier.cpp Block/divider.cpp Block/adder1w1a2w2a3w3to1w1a2w1.cpp Block/adder1w1a2w1to1w1a2w2a3w3.cpp Type/abstractType.cpp Type/onedecimalnumber.cpp Type/twodecimalnumbers.cpp Type/threedecimalnumbers.cpp Port/port.cpp Wire/wire.cpp values.cpp Type/registrtypes.cpp Block/blocksfactory.cpp Block/fillvaluesblock.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui values.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		/usr/lib64/qt5/bin/rcc \
		Resources/adder1w1a2w2a3w3to1w1a2w1.png \
		Resources/adder.png \
		Resources/subtractor.png \
		Resources/divider.png \
		Resources/adder1w1a2w1to1w1a2w2a3w3.png \
		Resources/multiplier.png
	/usr/lib64/qt5/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib64/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -std=gnu++14 -O2 -Wall -W -dM -E -o moc_predefs.h /usr/lib64/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_port.cpp moc_fillvaluesblock.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_port.cpp moc_fillvaluesblock.cpp
moc_mainwindow.cpp: ui_mainwindow.h \
		Block/abstractBlock.h \
		Port/port.h \
		Type/abstractType.h \
		Wire/wire.h \
		mainwindow.h \
		Type/registrtypes.h \
		Type/onedecimalnumber.h \
		Type/twodecimalnumbers.h \
		Type/threedecimalnumbers.h \
		ui_values.h \
		Block/fillvaluesblock.h \
		mainwindow.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/rhulka/programovani/ICP/ICP -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-redhat-linux -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-redhat-linux/7/include -I/usr/local/include -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_port.cpp: Type/abstractType.h \
		Wire/wire.h \
		mainwindow.h \
		ui_mainwindow.h \
		Block/abstractBlock.h \
		Port/port.h \
		ui_values.h \
		Block/fillvaluesblock.h \
		Type/registrtypes.h \
		Type/onedecimalnumber.h \
		Type/twodecimalnumbers.h \
		Type/threedecimalnumbers.h \
		Port/port.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/rhulka/programovani/ICP/ICP -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-redhat-linux -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-redhat-linux/7/include -I/usr/local/include -I/usr/include Port/port.h -o moc_port.cpp

moc_fillvaluesblock.cpp: ui_values.h \
		Block/abstractBlock.h \
		Port/port.h \
		Type/abstractType.h \
		Wire/wire.h \
		mainwindow.h \
		ui_mainwindow.h \
		Type/registrtypes.h \
		Type/onedecimalnumber.h \
		Type/twodecimalnumbers.h \
		Type/threedecimalnumbers.h \
		Block/fillvaluesblock.h \
		Block/fillvaluesblock.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/rhulka/programovani/ICP/ICP -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/c++/7/x86_64-redhat-linux -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-redhat-linux/7/include -I/usr/local/include -I/usr/include Block/fillvaluesblock.h -o moc_fillvaluesblock.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_values.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_values.h
ui_mainwindow.h: mainwindow.ui \
		/usr/lib64/qt5/bin/uic
	/usr/lib64/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_values.h: values.ui \
		/usr/lib64/qt5/bin/uic
	/usr/lib64/qt5/bin/uic values.ui -o ui_values.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		ui_mainwindow.h \
		Block/abstractBlock.h \
		Port/port.h \
		Type/abstractType.h \
		Wire/wire.h \
		ui_values.h \
		Block/fillvaluesblock.h \
		Type/registrtypes.h \
		Type/onedecimalnumber.h \
		Type/twodecimalnumbers.h \
		Type/threedecimalnumbers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h \
		Block/abstractBlock.h \
		Port/port.h \
		Type/abstractType.h \
		Wire/wire.h \
		ui_values.h \
		Block/fillvaluesblock.h \
		Type/registrtypes.h \
		Type/onedecimalnumber.h \
		Type/twodecimalnumbers.h \
		Type/threedecimalnumbers.h \
		Block/blocksfactory.h \
		Block/adder.h \
		Block/subtractor.h \
		Block/multiplier.h \
		Block/divider.h \
		Block/adder1w1a2w1to1w1a2w2a3w3.h \
		Block/adder1w1a2w2a3w3to1w1a2w1.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

abstractBlock.o: Block/abstractBlock.cpp Block/abstractBlock.h \
		Port/port.h \
		Type/abstractType.h \
		Wire/wire.h \
		mainwindow.h \
		ui_mainwindow.h \
		Type/registrtypes.h \
		Type/onedecimalnumber.h \
		Type/twodecimalnumbers.h \
		Type/threedecimalnumbers.h \
		ui_values.h \
		Block/fillvaluesblock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o abstractBlock.o Block/abstractBlock.cpp

adder.o: Block/adder.cpp Block/adder.h \
		Block/abstractBlock.h \
		Port/port.h \
		Type/abstractType.h \
		Wire/wire.h \
		mainwindow.h \
		ui_mainwindow.h \
		Type/registrtypes.h \
		Type/onedecimalnumber.h \
		Type/twodecimalnumbers.h \
		Type/threedecimalnumbers.h \
		ui_values.h \
		Block/fillvaluesblock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adder.o Block/adder.cpp

subtractor.o: Block/subtractor.cpp Block/subtractor.h \
		Block/abstractBlock.h \
		Port/port.h \
		Type/abstractType.h \
		Wire/wire.h \
		mainwindow.h \
		ui_mainwindow.h \
		Type/registrtypes.h \
		Type/onedecimalnumber.h \
		Type/twodecimalnumbers.h \
		Type/threedecimalnumbers.h \
		ui_values.h \
		Block/fillvaluesblock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o subtractor.o Block/subtractor.cpp

multiplier.o: Block/multiplier.cpp Block/multiplier.h \
		Block/abstractBlock.h \
		Port/port.h \
		Type/abstractType.h \
		Wire/wire.h \
		mainwindow.h \
		ui_mainwindow.h \
		Type/registrtypes.h \
		Type/onedecimalnumber.h \
		Type/twodecimalnumbers.h \
		Type/threedecimalnumbers.h \
		ui_values.h \
		Block/fillvaluesblock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o multiplier.o Block/multiplier.cpp

divider.o: Block/divider.cpp Block/divider.h \
		Block/abstractBlock.h \
		Port/port.h \
		Type/abstractType.h \
		Wire/wire.h \
		mainwindow.h \
		ui_mainwindow.h \
		Type/registrtypes.h \
		Type/onedecimalnumber.h \
		Type/twodecimalnumbers.h \
		Type/threedecimalnumbers.h \
		ui_values.h \
		Block/fillvaluesblock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o divider.o Block/divider.cpp

adder1w1a2w2a3w3to1w1a2w1.o: Block/adder1w1a2w2a3w3to1w1a2w1.cpp Block/adder1w1a2w2a3w3to1w1a2w1.h \
		Block/abstractBlock.h \
		Port/port.h \
		Type/abstractType.h \
		Wire/wire.h \
		mainwindow.h \
		ui_mainwindow.h \
		Type/registrtypes.h \
		Type/onedecimalnumber.h \
		Type/twodecimalnumbers.h \
		Type/threedecimalnumbers.h \
		ui_values.h \
		Block/fillvaluesblock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adder1w1a2w2a3w3to1w1a2w1.o Block/adder1w1a2w2a3w3to1w1a2w1.cpp

adder1w1a2w1to1w1a2w2a3w3.o: Block/adder1w1a2w1to1w1a2w2a3w3.cpp Block/adder1w1a2w1to1w1a2w2a3w3.h \
		Block/abstractBlock.h \
		Port/port.h \
		Type/abstractType.h \
		Wire/wire.h \
		mainwindow.h \
		ui_mainwindow.h \
		Type/registrtypes.h \
		Type/onedecimalnumber.h \
		Type/twodecimalnumbers.h \
		Type/threedecimalnumbers.h \
		ui_values.h \
		Block/fillvaluesblock.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adder1w1a2w1to1w1a2w2a3w3.o Block/adder1w1a2w1to1w1a2w2a3w3.cpp

abstractType.o: Type/abstractType.cpp Type/abstractType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o abstractType.o Type/abstractType.cpp

onedecimalnumber.o: Type/onedecimalnumber.cpp Type/onedecimalnumber.h \
		Type/abstractType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o onedecimalnumber.o Type/onedecimalnumber.cpp

twodecimalnumbers.o: Type/twodecimalnumbers.cpp Type/twodecimalnumbers.h \
		Type/abstractType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o twodecimalnumbers.o Type/twodecimalnumbers.cpp

threedecimalnumbers.o: Type/threedecimalnumbers.cpp Type/threedecimalnumbers.h \
		Type/abstractType.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o threedecimalnumbers.o Type/threedecimalnumbers.cpp

port.o: Port/port.cpp Port/port.h \
		Type/abstractType.h \
		Wire/wire.h \
		mainwindow.h \
		ui_mainwindow.h \
		Block/abstractBlock.h \
		Block/fillvaluesblock.h \
		ui_values.h \
		Type/registrtypes.h \
		Type/onedecimalnumber.h \
		Type/twodecimalnumbers.h \
		Type/threedecimalnumbers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o port.o Port/port.cpp

wire.o: Wire/wire.cpp Wire/wire.h \
		mainwindow.h \
		ui_mainwindow.h \
		Block/abstractBlock.h \
		Port/port.h \
		Type/abstractType.h \
		ui_values.h \
		Block/fillvaluesblock.h \
		Type/registrtypes.h \
		Type/onedecimalnumber.h \
		Type/twodecimalnumbers.h \
		Type/threedecimalnumbers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wire.o Wire/wire.cpp

values.o: values.cpp Port/port.h \
		Type/abstractType.h \
		Wire/wire.h \
		mainwindow.h \
		ui_mainwindow.h \
		Block/abstractBlock.h \
		Block/fillvaluesblock.h \
		ui_values.h \
		Type/registrtypes.h \
		Type/onedecimalnumber.h \
		Type/twodecimalnumbers.h \
		Type/threedecimalnumbers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o values.o values.cpp

registrtypes.o: Type/registrtypes.cpp Type/registrtypes.h \
		Type/onedecimalnumber.h \
		Type/abstractType.h \
		Type/twodecimalnumbers.h \
		Type/threedecimalnumbers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o registrtypes.o Type/registrtypes.cpp

blocksfactory.o: Block/blocksfactory.cpp Block/blocksfactory.h \
		Block/adder.h \
		Block/abstractBlock.h \
		Port/port.h \
		Type/abstractType.h \
		Wire/wire.h \
		mainwindow.h \
		ui_mainwindow.h \
		Type/registrtypes.h \
		Type/onedecimalnumber.h \
		Type/twodecimalnumbers.h \
		Type/threedecimalnumbers.h \
		ui_values.h \
		Block/fillvaluesblock.h \
		Block/subtractor.h \
		Block/multiplier.h \
		Block/divider.h \
		Block/adder1w1a2w1to1w1a2w2a3w3.h \
		Block/adder1w1a2w2a3w3to1w1a2w1.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o blocksfactory.o Block/blocksfactory.cpp

fillvaluesblock.o: Block/fillvaluesblock.cpp Block/fillvaluesblock.h \
		ui_values.h \
		Block/abstractBlock.h \
		Port/port.h \
		Type/abstractType.h \
		Wire/wire.h \
		mainwindow.h \
		ui_mainwindow.h \
		Type/registrtypes.h \
		Type/onedecimalnumber.h \
		Type/twodecimalnumbers.h \
		Type/threedecimalnumbers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fillvaluesblock.o Block/fillvaluesblock.cpp

qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_resources.o qrc_resources.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_port.o: moc_port.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_port.o moc_port.cpp

moc_fillvaluesblock.o: moc_fillvaluesblock.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fillvaluesblock.o moc_fillvaluesblock.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

